include:
  - remote: 'https://forge.dgfip.finances.rie.gouv.fr/dgfip/design/gitlab/gitlab-templates/-/raw/master/rpmbuild.gitlab-ci.yml'

.buildrpm:
  before_script:
    - git config --global --add safe.directory ${PWD}
    - sudo yum-config-manager --disable '*' >/dev/null
    - sudo yum-config-manager --add-repo=${CONFIG_REPO_URL}
  script:
    - tar --exclude-vcs --transform="s%^%${NAME}-${CI_COMMIT_TAG}/%rS" -czf $(rpm --eval '%_sourcedir')/${NAME}-${CI_COMMIT_TAG}.tar.gz *
    - rpmbuild -ba rpmautospec.spec

buildrpm/el7:
  before_script:
    - sudo cp macros.rpmautospec /etc/rpm/