include:
  - remote: 'https://forge.dgfip.finances.rie.gouv.fr/dgfip/design/gitlab/gitlab-templates/-/raw/master/rpmbuild.gitlab-ci.yml'

.buildrpm:
  before_script:
    - git config --global --add safe.directory ${PWD}
    - sudo yum-config-manager --disable '*' >/dev/null
    - sudo yum-config-manager --add-repo=${CONFIG_REPO_URL}
  script:
    - tar -czf $(rpm --eval '%_sourcedir')/$(rpmspec -q --qf "%{Name}-%{Version}.tar.gz\n" rpmautospec.spec) *
    - rpmbuild -ba rpmautospec.spec
  after_script:
    - cp "/home/rpmbuilder/rpmbuild/RPMS/${ARCH}/${CI_PROJECT_NAME}-${VERSION}-${RELEASE}.${ARCH}.rpm" /var/tmp
    - cp "/home/rpmbuilder/rpmbuild/SRPMS/${CI_PROJECT_NAME}-${VERSION}-${RELEASE}.src.rpm" /var/tmp
    - '${CURL} -H "Authorization: Basic ${BASIC_AUTH}" -T /var/tmp/${CI_PROJECT_NAME}-${VERSION}-${RELEASE}.${ARCH}.rpm ${REPO_URL}/'

buildrpm/el7:
  before_script:
    - sudo cp macros.rpmautospec /etc/rpm/