include:
  - remote: 'https://forge.dgfip.finances.rie.gouv.fr/dgfip/design/gitlab/gitlab-templates/-/raw/master/rpmbuild.gitlab-ci.yml'

.buildrpm:
  before_script:
    - git config --global --add safe.directory ${PWD}
    - sudo yum-config-manager --disable '*' >/dev/null
    - sudo yum-config-manager --add-repo=${CONFIG_REPO_URL}
  script:
    - rpmbuild -ba rpmautospec.spec