include:
  - remote: 'https://forge.dgfip.finances.rie.gouv.fr/dgfip/design/gitlab/gitlab-templates/-/raw/master/rpmbuild.gitlab-ci.yml'

.buildrpm:
  before_script:
    - git config --global --add safe.directory ${PWD}
    - export NAME=rpmautospec
    - export VERSION="${CI_COMMIT_TAG}"
    - export RELEASE="$(rpmspec -q --qf '%{release}' ${NAME}.spec)"
    - sudo yum-config-manager --disable '*' >/dev/null
    - sudo yum-config-manager --add-repo=${CONFIG_REPO_URL}
  script:
    - rpmbuild -ba ${NAME}.spec)